-- github.com/DaniAngelov

CONSTRAINTS:

FOREIGN KEYS:
---


-- TABLE EMPLOYEES:

ALTER TABLE EMPLOYEES ADD CONSTRAINT VEHICLES_ID_FK FOREIGN KEY(VEHICLES_ID) REFERENCES VEHICLES(ID)
ALTER TABLE EMPLOYEES ADD CONSTRAINT EXPERIENCE_ID_FK FOREIGN KEY(EXPERIENCE_ID) REFERENCES EXPERIENCE(ID)
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPLOYEE_TEAMS_ID_FK FOREIGN KEY(EMPLOYEE_TEAMS_ID) REFERENCES EMPLOYEE_TEAMS(ID)

-- TABLE SHIFTS :

ALTER TABLE SHIFTS ADD CONSTRAINT EMPLOYEES_ID_FK FOREIGN KEY(EMPLOYEES_ID) REFERENCES EMPLOYEES(ID)

-- TABLE SIGNALS :

ALTER TABLE SIGNALS ADD CONSTRAINT SECURED_AREAS_ID_FK FOREIGN KEY(SECURED_AREAS_ID) REFERENCES SECURED_AREAS(ID)
ALTER TABLE SIGNALS ADD CONSTRAINT EMPLOYEE_TEAMS_ID_SIGNALS_FK FOREIGN KEY(EMPLOYEE_TEAMS_ID) REFERENCES EMPLOYEE_TEAMS(ID)

-- TABLE SECURED AREAS:

ALTER TABLE SECURED_AREAS ADD CONSTRAINT CUSTOMERS_ID_FK FOREIGN KEY(CUSTOMERS_ID) REFERENCES CUSTOMERS(ID)
ALTER TABLE SECURED_AREAS ADD CONSTRAINT SENSORS_FAMILIES_ID_FK FOREIGN KEY(SENSORS_FAMILIES_ID) REFERENCES SENSORS_FAMILIES(ID)

-- TABLE SENSOR DETECTORS:
ALTER TABLE SENSOR_DETECTORS ADD CONSTRAINT SENSORS_FAMILY_ID_SENSORS_FK FOREIGN KEY(SENSORS_FAMILY_ID) REFERENCES SENSORS_FAMILIES(ID)

---

--CHECK : 

-- VEHICLES :

ALTER TABLE VEHICLES ADD CONSTRAINT CHK_HORSE_POWER CHECK (HORSE_POWER > 50 AND HORSE_POWER < 1000)
ALTER TABLE VEHICLES ADD CONSTRAINT CHK_ISDRIVABLE CHECK (ISDRIVABLE = 0 OR ISDRIVABLE = 1)

-- EMPLOYEES : 

ALTER TABLE EMPLOYEES ADD CONSTRAINT CHK_GENDER CHECK (GENDER LIKE 'MALE' OR GENDER LIKE 'FEMALE')
ALTER TABLE EMPLOYEES ADD CONSTRAINT CHK_AGE CHECK (AGE > 20 AND AGE < 50)
ALTER TABLE EMPLOYEES ADD CONSTRAINT CHK_PHONE_NUMBER CHECK (PHONE_NUMBER LIKE '+359%')

-- EMPLOYEE TEAMS:

ALTER TABLE EMPLOYEE_TEAMS ADD CONSTRAINT CHK_TEAM_SIZE CHECK (TEAM_SIZE >= 2 AND TEAM_SIZE <= 5)

-- SHIFTS:
ALTER TABLE SHIFTS ADD CONSTRAINT CHK_TYPE CHECK (TYPE LIKE 'DAY' OR TYPE LIKE 'NIGHT')
ALTER TABLE Shifts ADD CONSTRAINT CHK_TIME CHECK( Date_When_Starts <= Date_When_Ends)
ALTER TABLE SHIFTS ADD CONSTRAINT CHK_IS_HOLIDAY CHECK (ISHOLIDAY LIKE '1' OR ISHOLIDAY LIKE '0')
ALTER TABLE SHIFTS ADD CONSTRAINT CHK_IS_WEEKEND CHECK (ISWEEKEND LIKE '1' OR ISWEEKEND LIKE '0')

-- EXPERIENCE:

ALTER TABLE EXPERIENCE ADD CONSTRAINT CHK_YEARS CHECK (YEARS >= 0)
ALTER TABLE EXPERIENCE ADD CONSTRAINT CHK_NUMBER_OF_COMPANIES CHECK (NUMBER_OF_COMPANIES >= 0)

-- CUSTOMERS:

ALTER TABLE CUSTOMERS ADD CONSTRAINT CHK_PHONE_NUMBER_CUSTOMER CHECK (PHONE_NUMBER LIKE '+359%')
ALTER TABLE CUSTOMERS ADD CONSTRAINT CHK_GENDER_CUSTOMER CHECK (GENDER LIKE 'MALE' OR GENDER LIKE 'FEMALE')

-- SECURED_AREAS :

ALTER TABLE SECURED_AREAS ADD CONSTRAINT CHK_SECURITY_LEVEL CHECK (SECURITY_LEVEL >= 1 AND SECURITY_LEVEL <= 10)
ALTER TABLE SECURED_AREAS ADD CONSTRAINT CHK_BUILDING_LEVEL CHECK (BUILDING_LEVEL >= 0)
ALTER TABLE SECURED_AREAS ADD CONSTRAINT CHK_SIZE CHECK (SIZE >= 0)

-- SENSORS_FAMILIES :

ALTER TABLE SENSORS_FAMILIES ADD CONSTRAINT CHK_SIZE_SENSORS CHECK (SIZE >= 0)


-- SENSORS_DETECTORS :

ALTER TABLE SENSOR_DETECTORS ADD CONSTRAINT CHK_RANGE CHECK (RANGE >= 0)
